src/export/urls.py
from django.urls import path

from . import views

app_name = 'export'

urlpatterns = [
    path('excel/', views.export_excel, name='excel'),
]

src/family_finances/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('transactions.urls', namespace='transactions')),
    path('export/', include('export.urls', namespace='export')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.v1.urls', namespace='api_v1')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


# Генерация динамической документации
schema_view = get_schema_view(
    info=openapi.Info(
        title="Family Finances API",
        default_version='v1',
        description="Family Finances API"
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)
urlpatterns += [
    re_path(
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'
    ),
    path(
        'redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]

src/transactions/urls.py
from django.urls import path

from . import views

app_name = 'transactions'

urlpatterns = [
    path('apply_period/', views.apply_period, name='apply_period'),
    path('change_period', views.ChangePeriod.as_view(), name='change_period'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('transactions/', views.TransactionView.as_view(), name='transactions'),
    path('', views.HomePageView.as_view(), name='home'),
]

src/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('ajax-login/', views.login_ajax, name='ajax_login'),
    path('telegram-auth/', views.telegram_auth, name='telegram_auth'),
    path('registration/', views.registration, name='registration'),
    path('webapp-auth/', views.webapp_auth, name='webapp_auth'),
    path('webapp/', views.webapp, name='webapp'),
]

src/transactions/forms.py
from django import forms
from users.models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput,
        label='Пароль'
    )

    class Meta:
        model = User
        fields = ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Имя пользователя уже занято')
        return username

src/api/v1/transactions/views.py
from django.db import transaction, IntegrityError
from django_filters.rest_framework import DjangoFilterBackend
from drf_yasg.utils import swagger_auto_schema
from rest_framework import filters, status
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError
from rest_framework.generics import get_object_or_404
from rest_framework.mixins import (
    ListModelMixin,
    CreateModelMixin,
    RetrieveModelMixin
)
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet, GenericViewSet

from tools.transactions import get_summary_report
from transactions.models import Summary, Space
from users.models import User
from .serializers import (
    TransactionCreateSerializer,
    SummaryDetailSerializer,
    TransactionDetailSerializer,
    LinkUserToSpaceSerializer,
    UnlinkUserToSpaceSerializer,
    SpaceSerializer,
    SummaryCreateSerializer,
)


class TransactionViewSet(
    ListModelMixin,
    CreateModelMixin,
    RetrieveModelMixin,
    GenericViewSet
):
    """Отображение и создание для transactions."""

    serializer_class = TransactionCreateSerializer
    filter_backends = (DjangoFilterBackend, filters.SearchFilter)
    filterset_fields = ('period_month', 'period_year', 'space__id')
    search_fields = ('^group_name',)

    def get_user(self):
        return get_object_or_404(User, pk=self.kwargs['user_id'])

    def get_queryset(self):
        if getattr(self, 'swagger_fake_view', False):
            return None
        return self.get_user().transactions

    def get_serializer_class(self):
        if self.action == 'create':
            return TransactionCreateSerializer
        return TransactionDetailSerializer

    def perform_create(self, serializer):
        user = self.get_user()
        with transaction.atomic():
            serializer.save(
                author=user,
                space=user.core_settings.current_space,
                period_month=user.core_settings.current_month,
                period_year=user.core_settings.current_year
            )
            summary = Summary.objects.get(
                space=user.core_settings.current_space,
                period_month=user.core_settings.current_month,
                period_year=user.core_settings.current_year,
                type_transaction=serializer.validated_data['type_transaction'],
                group_name=serializer.validated_data['group_name']
            )
            summary.fact_value += serializer.validated_data[
                'value_transaction'
            ]
            summary.save()


class SummaryViewSet(ModelViewSet):
    """Просмотр Summary (отчета), CRUD для статей (групп операций)."""

    filter_backends = (DjangoFilterBackend, filters.SearchFilter)
    filterset_fields = ('group_name', 'type_transaction')
    search_fields = ('^group_name',)

    def get_user(self):
        return get_object_or_404(User, pk=self.kwargs['user_id'])

    def get_queryset(self):
        if getattr(self, 'swagger_fake_view', False):
            return None
        user = self.get_user()
        return Summary.objects.filter(
            space=user.core_settings.current_space,
            period_month=user.core_settings.current_month,
            period_year=user.core_settings.current_year
        )

    def get_serializer_class(self):
        if self.action in ('create', 'update'):
            return SummaryCreateSerializer
        return SummaryDetailSerializer

    def perform_create(self, serializer):
        try:
            serializer.save(
                space=self.get_user().core_settings.current_space,
                period_month=self.get_user().core_settings.current_month,
                period_year=self.get_user().core_settings.current_year
            )
        except IntegrityError:
            raise ValidationError(
                'Не уникальное имя группы для текущего периода и базы.'
            )

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        summary_report = get_summary_report(queryset)
        serializer = self.get_serializer(queryset, many=True)
        return Response(
            {
                'sum_income_plan': summary_report.income_plan,
                'sum_income_fact': summary_report.income_fact,
                'sum_expense_plan': summary_report.expense_plan,
                'sum_expense_fact': summary_report.expense_fact,
                'balance_plan':
                    summary_report.income_plan - summary_report.expense_plan,
                'balance_fact':
                    summary_report.income_fact - summary_report.expense_fact,
                'summary': serializer.data
            }
        )


class PeriodViewSet(GenericViewSet):
    """Просмотр периодов в текущем пространстве пользователя."""
    pagination_class = None

    def get_user(self):
        return get_object_or_404(User, pk=self.kwargs['user_id'])

    def get_queryset(self):
        if getattr(self, 'swagger_fake_view', False):
            return None
        user = self.get_user()
        return Summary.objects.filter(
            space=user.core_settings.current_space,
        )

    @action(detail=False, methods=['get'], url_path='years')
    def years(self, request, user_id):
        return Response(
            {
                'years': list(
                    self.filter_queryset(self.get_queryset())
                    .order_by('period_year')
                    .values_list('period_year', flat=True)
                    .distinct()
                )
            }
        )

    @action(detail=False, methods=['get'], url_path='months')
    def months(self, request, user_id):
        year = request.query_params.get('year')
        if not year:
            raise ValidationError('Запрос не содержит год.')
        try:
            return Response({
                'year': year,
                'months': list(
                    self.filter_queryset(self.get_queryset())
                    .filter(period_year=year)
                    .order_by('period_year')
                    .values_list('period_month', flat=True)
                    .distinct()
                )
            })
        except (TypeError, ValueError) as e:
            raise ValidationError(e)


class SpaceViewSet(ModelViewSet):
    """CRUD для пространств пользователей."""

    serializer_class = SpaceSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('^name',)

    def get_user(self):
        return get_object_or_404(User, pk=self.kwargs['user_id'])

    def get_queryset(self):
        if getattr(self, 'swagger_fake_view', False):
            return None
        return Space.objects.filter(user_id=self.kwargs['user_id'])

    def perform_create(self, serializer):
        serializer.save(user=self.get_user())

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        user = self.get_user()
        serializer = self.get_serializer(queryset, many=True)
        return Response(
            {
                'owner_id': user.id,
                'owner_username': user.username,
                'spaces': serializer.data
            }
        )

    @swagger_auto_schema(
        tags=['Подключение/отключение пользователей'],
        operation_description='Подключение пользователя к пространству.',
        responses={
            status.HTTP_200_OK:
                'Пользователь username '
                '(id 1) подключен к базе '
                'user_base '
                '(id 11) '
                'пользователя username_2 '
                '(id 22).'
        },
        request_body=LinkUserToSpaceSerializer
    )
    @action(detail=True, methods=['post'], url_path='link_user')
    def link_user(self, request, user_id, pk=None):
        serializer = LinkUserToSpaceSerializer(
            data=request.data,
            context={'space_id': pk, 'user_id': int(user_id)}
        )
        serializer.is_valid(raise_exception=True)
        instance = serializer.save()
        return Response(
            {
                'status': f'Пользователь {instance.linked_user.username} '
                          f'(id {instance.linked_user.id}) подключен к базе '
                          f'{instance.space.name} '
                          f'(id {instance.space.id}) '
                          f'пользователя {instance.space.user.username} '
                          f'(id {instance.space.user.id}).'
            },
            status=status.HTTP_200_OK
        )

    @swagger_auto_schema(
        tags=['Подключение/отключение пользователей'],
        operation_description='Отключение пользователя от пространства.',
        responses={
            status.HTTP_200_OK:
                'Пользователь username '
                '(id 1) отключен от базы '
                'user_base '
                '(id 11) '
                'пользователя username_2 '
                '(id 22).'
        },
        request_body=UnlinkUserToSpaceSerializer
    )
    @action(detail=True, methods=['post'], url_path='unlink_user')
    def unlink_user(self, request, user_id, pk=None):
        serializer = UnlinkUserToSpaceSerializer(
            data=request.data,
            context={'space_id': pk, 'user_id': int(user_id)}
        )
        serializer.is_valid(raise_exception=True)
        vd = serializer.validated_data
        serializer.delete(vd)
        return Response(
            {
                'status': f'Пользователь {vd['linked_user'].username} '
                          f'(id {vd['linked_user'].id}) отключен от базы '
                          f'{vd['space'].name} '
                          f'(id {vd['space'].id}) '
                          f'пользователя {vd['space'].user.username} '
                          f'(id {vd['space'].user.id}).'
            },
            status=status.HTTP_200_OK
        )

src/transactions/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.generic import TemplateView

from tools.transactions import get_summary_report
from .models import Summary, Transaction


class HomePageView(TemplateView):
    template_name = 'transactions/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = settings.PROJECT_TITLE
        return context


class SummaryView(LoginRequiredMixin, TemplateView):
    """Отчет по периоду."""

    template_name = 'transactions/summary.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_month = self.request.user.core_settings.current_month
        current_year = self.request.user.core_settings.current_year
        current_space = self.request.user.core_settings.current_space
        summary = Summary.objects.filter(
            period_month=current_month,
            period_year=current_year,
            space=current_space
        )
        summary_report = get_summary_report(summary)
        context.update(
            {
                'title': settings.PROJECT_TITLE,
                'incomes': summary.filter(type_transaction='income'),
                'expenses': summary.filter(type_transaction='expense'),
                'sum_income_plan': summary_report.income_plan,
                'sum_income_fact': summary_report.income_fact,
                'sum_expense_plan': summary_report.expense_plan,
                'sum_expense_fact': summary_report.expense_fact,
                'balance_plan':
                    summary_report.income_plan - summary_report.expense_plan,
                'balance_fact':
                    summary_report.income_fact - summary_report.expense_fact,
                'current_month': current_month,
                'current_year': current_year,
                'current_space': current_space,
                'next': self.request.path,
            }
        )
        return context


class TransactionView(LoginRequiredMixin, TemplateView):
    """Отчет по транзакциям за период."""

    template_name = 'transactions/transactions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_month = self.request.user.core_settings.current_month
        current_year = self.request.user.core_settings.current_year
        current_space = self.request.user.core_settings.current_space
        transactions = Transaction.objects.filter(
            space=self.request.user.core_settings.current_space,
            period_month=self.request.user.core_settings.current_month,
            period_year=self.request.user.core_settings.current_year
        )
        context.update(
            {
                'title': settings.PROJECT_TITLE,
                'transactions': transactions,
                'current_month': current_month,
                'current_year': current_year,
                'current_space': current_space,
                'next': self.request.path,
            }
        )
        return context


class ChangePeriod(LoginRequiredMixin, TemplateView):
    template_name = 'transactions/change_period.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        periods = Summary.objects.filter(
            space=self.request.user.core_settings.current_space
        ).values('period_month', 'period_year')
        sorted_unique_periods = sorted(
            {f'{period["period_year"]}_{period['period_month']}' for period in periods},
            reverse=True
        )
        context.update({'periods': sorted_unique_periods, 'next': self.request.GET.get('next', '/')})
        return context


@login_required
def apply_period(request):
    """Применение смены периода и редирект на предыдущую страницу."""
    period = request.GET.get('period')
    next_url = request.GET.get('next', '/')

    if period:
        year, month = map(int, period.split('_'))
        request.user.core_settings.current_year = year
        request.user.core_settings.current_month = month
        request.user.core_settings.save()

    if not url_has_allowed_host_and_scheme(next_url, allowed_hosts={request.get_host()}):
        next_url = '/'

    return redirect(next_url)

src/templates/transactions/change_period.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
      <h2>Выберите период:</h2>
        {% for period in periods %}
          <p>
            <a class="navbar-brand text-white" href="{% url 'transactions:apply_period' %}?period={{ period|urlencode }}&next={{ next|urlencode }}">
              {{ period }}
            </a>
          </p>
        {% endfor %}
    </div>
{% endblock %}

src/templates/transactions/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2>Добро пожаловать!</h2>
        {% if user.is_authenticated %}
            <p>Используйте меню слева для добавления транзакций и просмотра отчетов.</p>
        {% else %}
            <p>Для продолжения работы необходимо авторизоваться.</p>
        {% endif %}
    </div>
{% endblock %}

src/templates/transactions/summary.html
{% extends 'base.html' %}
{% load humanize %}

{% block core_settings_info %}
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">
          📅 <a class="navbar-brand text-white" href="{% url 'transactions:change_period' %}?next={{ next|urlencode }}">{{ current_month }}.{{ current_year }}</a>
        </span>
        <span class="navbar-brand mb-0 h1">📓 {{ current_space.name }} ({{ current_space.user.username }})</span>
      </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="main-content" id="main-content">
        <div class="container mt-4">
            <div class="row">
                <!-- Блок с доходами -->
                <div class="col-md-6 mb-4">
                    <h5 class="text-center">Доходы</h5>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table-dark">
                                <tr>
                                    <th>Группа</th>
                                    <th>План</th>
                                    <th>Факт</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for income in incomes %}
                                    <tr>
                                        <td>{{ income.group_name }}</td>
                                        <td>{{ income.plan_value|intcomma }}</td>
                                        <td>{{ income.fact_value|intcomma }}</td>
                                    </tr>
                                {% empty %}
                                    <tr><td colspan="3" class="text-center">Нет данных</td></tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
    
                <!-- Блок с расходами -->
                <div class="col-md-6 mb-4">
                    <h5 class="text-center">Расходы</h5>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table-dark">
                                <tr>
                                    <th>Группа</th>
                                    <th>План</th>
                                    <th>Факт</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for expense in expenses %}
                                <tr>
                                    <td>{{ expense.group_name }}</td>
                                    <td>{{ expense.plan_value|intcomma }}</td>
                                    <td>{{ expense.fact_value|intcomma }}</td>
                                </tr>
                                {% empty %}
                                    <tr><td colspan="3" class="text-center">Нет данных</td></tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center">
                <h5 class="text-center">Свод</h5>
                <div class="col-md-6 mb-4">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table-dark">
                                <tr>
                                    <th>Тип</th>
                                    <th>План</th>
                                    <th>Факт</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Итого доходы</td>
                                    <td>{{ sum_income_plan|intcomma }}</td>
                                    <td>{{ sum_income_fact|intcomma }}</td>
                                </tr>
                                <tr>
                                    <td>Итого расходы</td>
                                    <td>{{ sum_expense_plan|intcomma }}</td>
                                    <td>{{ sum_expense_fact|intcomma }}</td>
                                </tr>
                                <tr>
                                    <td>Сальдо</td>
                                    <td>{{ balance_plan|intcomma }}</td>
                                    <td>{{ balance_fact|intcomma }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/transactions/transactions.html
{% extends 'base.html' %}
{% load humanize %}

{% block core_settings_info %}
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">
          📅 <a class="navbar-brand text-white" href="{% url 'transactions:change_period' %}?next={{ next|urlencode }}">{{ current_month }}.{{ current_year }}</a>
        </span>
        <span class="navbar-brand mb-0 h1">📓 {{ current_space.name }} ({{ current_space.user.username }})</span>
      </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="main-content" id="main-content">
        <div class="container mt-4">
            <div class="row justify-content-center">
                <h5 class="text-center">Операции</h5>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th>Дата</th>
                                <th>Тип</th>
                                <th>Статья</th>
                                <th>Значение</th>
                                <th>Описание</th>
                                <th>Автор</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for transaction in transactions %}
                                <tr>
                                    <td>{{ transaction.created_at|date:"d.m.Y" }}</td>
                                    {% if transaction.type_transaction == 'income' %}
                                        <td>Доход</td>
                                    {% else %}
                                        <td>Расход</td>
                                    {% endif %}
                                    <td>{{ transaction.group_name }}</td>
                                    <td>{{ transaction.value_transaction|intcomma }}</td>
                                    <td>{{ transaction.description }}</td>
                                    <td>{{ transaction.author.username }}</td>
                                </tr>
                            {% empty %}
                                <tr><td colspan="6" class="text-center">Нет данных</td></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-5">
        <a href="{% url 'export:excel' %}">
            <button class="btn btn-light me-2"
                    data-bs-toggle="popover"
                    data-bs-placement="top"
                    data-bs-trigger="focus"
                    data-bs-content="Кнопка не доступна из Telegram Webapp.
                    Для Telegram перейдите в меню бота - 'Просмотр'.">
                Экспорт в Excel
            </button>
        </a>
    </div>
    <script>
        // Инициализация всех popover на странице
        document.addEventListener('DOMContentLoaded', function () {
            const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
            const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl));
        });
    </script>
{% endblock %}