src/family_finances/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('transactions.urls', namespace='transactions')),
    path('export/', include('export.urls', namespace='export')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.v1.urls', namespace='api_v1')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


# Генерация динамической документации
schema_view = get_schema_view(
    info=openapi.Info(
        title="Family Finances API",
        default_version='v1',
        description="Family Finances API"
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)
urlpatterns += [
    re_path(
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'
    ),
    path(
        'redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]

src/transactions/urls.py
from django.urls import path

from . import views

app_name = 'transactions'

urlpatterns = [
    path('apply_period/', views.apply_period, name='apply_period'),
    path('change_period', views.ChangePeriod.as_view(), name='change_period'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('transactions/', views.TransactionView.as_view(), name='transactions'),
    path('', views.HomePageView.as_view(), name='home'),
]

src/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('ajax-login/', views.login_ajax, name='ajax_login'),
    path('telegram-auth/', views.telegram_auth, name='telegram_auth'),
    path('registration/', views.registration, name='registration'),
    path('webapp-auth/', views.webapp_auth, name='webapp_auth'),
    path('webapp/', views.webapp, name='webapp'),
]

src/templates/webapp/webapp.html
<!DOCTYPE html>
<html lang='ru'>
<head>
    <meta charset='UTF-8'>
    <title>Web App</title>
</head>
<body>

<script src='https://telegram.org/js/telegram-web-app.js'></script>
<script>
    Telegram.WebApp.ready();

    const initData = Telegram.WebApp.initData;

    console.log(initData)
    // Отправляем данные на сервер Django
    fetch('{% url 'users:webapp_auth' %}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ initData }),
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            console.log('Авторизация успешна!');
            // Перенаправляем на главную страницу
            window.location.href = '{% url 'transactions:summary' %}';
        } else {
            console.error('Ошибка авторизации:', data.error);
        }
    });
</script>


</body>
</html>