src/family_finances/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('transactions.urls', namespace='transactions')),
    path('export/', include('export.urls', namespace='export')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.v1.urls', namespace='api_v1')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


# Генерация динамической документации
schema_view = get_schema_view(
    info=openapi.Info(
        title="Family Finances API",
        default_version='v1',
        description="Family Finances API"
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)
urlpatterns += [
    re_path(
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'
    ),
    path(
        'redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]

src/transactions/urls.py
from django.urls import path

from . import views

app_name = 'transactions'

urlpatterns = [
    path('apply_period/', views.apply_period, name='apply_period'),
    path('change_period', views.ChangePeriod.as_view(), name='change_period'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('transactions/', views.TransactionView.as_view(), name='transactions'),
    path('', views.HomePageView.as_view(), name='home'),
]

src/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('ajax-login/', views.login_ajax, name='ajax_login'),
    path('telegram-auth/', views.telegram_auth, name='telegram_auth'),
    path('registration/', views.registration, name='registration'),
    path('webapp-auth/', views.webapp_auth, name='webapp_auth'),
    path('webapp/', views.webapp, name='webapp'),
]

src/templates/includes/auth_telegram.html
<script
    async src="https://telegram.org/js/telegram-widget.js?22"
    data-telegram-login="family_finance_2_bot"
    data-size="large"
    data-auth-url="https://ff2.501lab.ru.net/users/telegram-auth"
    data-request-access="write">
</script>

src/templates/includes/header.html
<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-custom">
    <div class="container-fluid">
        
        {% if user.is_authenticated %}
            <button class="btn btn-light me-2" id="menuButton">☰ Меню</button>
            <a class="navbar-brand text-white" href="{% url 'transactions:home' %}">{{ title }}</a>
            <!-- Кнопка пользователя (скрыта по умолчанию) -->
            <div class="d-flex" id="userButton" style="display: none;">
                <button class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="userDropdown">
                    <span id="username">{{ user }}</span>
                </button>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><a class="dropdown-item" href="{% url 'transactions:home' %}">Профиль</a></li>
                    <li>
                        <form method="post" action="{% url 'logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">Выйти</button>
                        </form>
                    </li>
                </ul>
            </div>
        {% else %}
            <a class="navbar-brand text-white" href="#">{{ title }}</a>
            <div class="d-flex" id="authButtons">
                <!-- Кнопки входа и регистрации -->
                <button class="btn btn-light me-2" data-bs-toggle="modal" data-bs-target="#loginModal">Войти</button>
                <button class="btn btn-light me-2" data-bs-toggle="modal" data-bs-target="#registrationModal">Регистрация</button>
            </div>
        {% endif %}
    </div>
</nav>

src/templates/includes/menu.html
<!-- Custom Sidebar -->
<div id="sidebar" class="container">
    <span class="close-btn" id="closeSidebar">&times;</span>
    <a href="{% url 'transactions:home' %}" class="menu-item">Главная</a>
{#    <a href="#" class="menu-item">Добавить транзакцию</a>#}
    <a href="{% url 'transactions:summary' %}" class="menu-item">Посмотреть отчет</a>
    <a href="{% url 'transactions:transactions' %}" class="menu-item">Посмотреть детализацию</a>
{#    <a href="#" class="menu-item">Сменить период</a>#}
</div>

src/templates/includes/modal_login.html
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Вход</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="loginForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Логин</label>
                        <input type="text" class="form-control" id="username" placeholder="Введите логин" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите пароль" required>
                    </div>
                    <button type="submit" class="btn btn-dark w-100">Войти</button>
                    <div id="loginError" class="text-danger mt-2"></div>
                </form>
                {% include 'includes/auth_telegram.html' %}
            </div>
        </div>
    </div>
</div>

src/templates/includes/modal_registration.html
<!-- Registration Modal -->
<div class="modal fade" id="registrationModal" tabindex="-1" aria-labelledby="registrationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="registrationModalLabel">Регистрация</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="registrationForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="registration_username" class="form-label">Логин</label>
                        <input type="text" class="form-control" id="registration_username" placeholder="Введите логин" required>
                    </div>
                    <div class="mb-3">
                        <label for="registration_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="registration_password" placeholder="Введите пароль" required>
                    </div>
                    <button type="submit" class="btn btn-dark w-100">Зарегистрироваться</button>
                    <div id="registrationError" class="text-danger mt-2"></div>
                </form>
                <div id="registrationSuccess" class="alert alert-success" style="display:none;"></div>
            </div>
        </div>
    </div>
</div>